export const FETCH_TRAININGS_START = 'FETCH_TRAININGS_START';
export const FETCH_TRAININGS_SUCCESS = 'FETCH_TRAININGS_SUCCESS';
export const FETCH_TRAININGS_FAIL = 'FETCH_TRAININGS_FAIL';
export const TRAINING_TO_SHOW_HANDLER = 'TRAINING_TO_SHOW_HANDLER';
export const TRAININGS_CLEAR_ERROR = 'TRAININGS_CLEAR_ERROR';
export const EDIT_TRAINING_IN_STORE = 'EDIT_TRAINING_IN_STORE';
export const DELETE_TRAINING_FROM_STORE = 'DELETE_TRAINING_FROM_STORE';

export const ADD_TRAINING_STEP_1 = 'ADD_TRAINING_STEP_1';
export const ADD_TRAINING_EDIT_FORM = 'ADD_TRAINING_EDIT_FORM';
export const ADD_SET = 'ADD_SET';
export const DELETE_SET = 'DELETE_SET';
export const CLEAR_ADD_TRAINING_FORM = 'CLEAR_ADD_TRAINING_FORM';
export const IS_EDIT_TRAINING = 'IS_EDIT_TRAINING';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';

