export const FETCH_TRAININGS_START = 'FETCH_TRAININGS_START';
export const FETCH_TRAININGS_SUCCESS = 'FETCH_TRAININGS_SUCCESS';
export const FETCH_TRAININGS_FAIL = 'FETCH_TRAININGS_FAIL';
export const TRAINING_TO_SHOW_HANDLER = 'TRAINING_TO_SHOW_HANDLER';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
