// Calendar
export const LOADING = 'LOADING';
export const GET_TRAININGS_SUCCESS = 'GET_TRAININGS_SUCCESS';
export const GET_TRAININGS_FAIL = 'GET_TRAININGS_FAIL';
export const SET_CALENDAR_STRUCTURE = 'SET_CALENDAR_STRUCTURE';
export const SET_PICKED_DATE = 'SET_PICKED_DATE';
export const SET_PICKED_MONTH = 'SET_PICKED_MONTH';
export const SET_DAYS_OF_WEEK = 'SET_DAYS_OF_WEEK';
export const MAP_TRAININGS_TO_CALENDAR = 'MAP_TRAININGS_TO_CALENDAR';
export const SET_PICKED_TRAININGS = 'SET_PICKED_TRAININGS';
export const DELETE_TRAINING = 'DELETE_TRAINING';
export const EDIT_TRAINING = 'EDIT_TRAINING';
export const ADD_TRAINING = 'ADD_TRAINING';

// Add training form
export const ADD_TRAINING_STEP_1 = 'ADD_TRAINING_STEP_1';
export const ADD_TRAINING_TO_EDIT_FORM = 'ADD_TRAINING_TO_EDIT_FORM';
export const ADD_SET = 'ADD_SET';
export const DELETE_SET = 'DELETE_SET';
export const RESET_ADD_TRAINING_FORM = 'RESET_ADD_TRAINING_FORM';
export const SET_ADD_TRAINING_FORM_EDIT_OPTION = 'SET_ADD_TRAINING_FORM_EDIT_OPTION';

// Authenticate
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';

// Big six
export const FETCH_BIG_SIX_SUCCESS = 'FETCH_BIG_SIX_SUCCESS';
export const FETCH_BIG_SIX_FAIL = 'FETCH_BIG_SIX_FAIL';

